### ISSUE TITLE
Erro build in Expo SDK 52 and MMKV 3.2.0

### ISSUE THREAD

**Issue by danieljuniorce** [mrousavy/react-native-mmkv#792]
Hey, I'm trying to build with npx expo run:android I'm getting this specific error from mmkv.

Expo: `52.0.28`
react-native-mmkv: `3.2.0`
JDK: 17

```
> Configure project :react-native-mmkv
[react-native-mmkv] Thank you for using react-native-mmkv ❤️
[react-native-mmkv] If you enjoy using react-native-mmkv, please consider sponsoring this project: https://github.com/sponsors/mrousavy

> Configure project :react-native-reanimated
Android gradle plugin: 8.6.0
Gradle: 8.10.2

> Task :app:processDebugMainManifest
/home/danieljuniorce/develop/fluke/whitelabel-app/android/app/src/debug/AndroidManifest.xml:6:5-162 Warning:
        application@android:usesCleartextTraffic was tagged at AndroidManifest.xml:6 to replace other declarations but no other declaration present
/home/danieljuniorce/develop/fluke/whitelabel-app/android/app/src/debug/AndroidManifest.xml Warning:
        provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present

> Task :react-native-mmkv:compileDebugJavaWithJavac FAILED
/home/danieljuniorce/develop/fluke/whitelabel-app/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:7: error: cannot find symbol
public class MmkvPlatformContextModule extends NativeMmkvPlatformContextSpec {
                                               ^
  symbol: class NativeMmkvPlatformContextSpec
/home/danieljuniorce/develop/fluke/whitelabel-app/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:15: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/danieljuniorce/develop/fluke/whitelabel-app/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:21: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/danieljuniorce/develop/fluke/whitelabel-app/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:19: error: cannot find symbol
    if (name.equals(MmkvPlatformContextModule.NAME)) {
                                             ^
  symbol:   variable NAME
  location: class MmkvPlatformContextModule
/home/danieljuniorce/develop/fluke/whitelabel-app/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:20: error: incompatible types: MmkvPlatformContextModule cannot be converted to NativeModule
      return new MmkvPlatformContextModule(reactContext);
             ^
/home/danieljuniorce/develop/fluke/whitelabel-app/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:31: error: cannot find symbol
              MmkvPlatformContextModule.NAME,
                                       ^
  symbol:   variable NAME
  location: class MmkvPlatformContextModule
/home/danieljuniorce/develop/fluke/whitelabel-app/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:33: error: cannot find symbol
                      MmkvPlatformContextModule.NAME,
                                               ^
  symbol:   variable NAME
  location: class MmkvPlatformContextModule
/home/danieljuniorce/develop/fluke/whitelabel-app/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:34: error: cannot find symbol
                      MmkvPlatformContextModule.NAME,
                                               ^
  symbol:   variable NAME
  location: class MmkvPlatformContextModule
Note: /home/danieljuniorce/develop/fluke/whitelabel-app/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.
```

**Comment by mrousavy** [comment]
hmm, are you using new arch?

**Comment by enavermate** [comment]
@danieljuniorce resolved by 

> app.json
```{
  "expo": {
    // ...
    "plugins": [
      [
        "expo-build-properties",
        {
          "ios": {
            "newArchEnabled": true
          },
          "android": {
            "newArchEnabled": true
          }
        }
      ]
    ]
  }
}
```

**Comment by enavermate** [comment]
@gabimoncha yes
![Image](https://github.com/user-attachments/assets/739f3f29-369f-44fc-8075-6a180fb7340f)

I've used last suggested by Expo package versions throw `npx expo install --check`
![Image](https://github.com/user-attachments/assets/0c6077ec-b528-4c6e-b139-409e423fb60c)

**Comment by gabimoncha** [comment]
cool. will give it a try then

**Comment by haivle** [comment]
I'm encountering the same issue with 
```
    expo: 52.0.35
    react-native: 0.76.7
```

**Comment by mimo-10** [comment]
Same issue, any suggestion 
expo version : 52.0.37

**Comment by mimo-10** [comment]
> [@danieljuniorce](https://github.com/danieljuniorce) resolved by
> 
> > app.json
> 
> ```
>   "expo": {
>     // ...
>     "plugins": [
>       [
>         "expo-build-properties",
>         {
>           "ios": {
>             "newArchEnabled": true
>           },
>           "android": {
>             "newArchEnabled": true
>           }
>         }
>       ]
>     ]
>   }
> }
> ```

it worked . i installed expo-build-properties and then added the plugin config as shown here.

**Comment by redbluenat** [comment]
I have the same problem, any ideas on how to fix it? 

    expo: 52.0.35
    react-native: 0.76.7

**Comment by gabimoncha** [comment]
@mrousavy is it possible that turbomodules is enabled only through expo-build-properties "newArchEnabled"

it seems that turbomodules is disabled either way, and has to be manually enabled in app.json
```
experiments: {
  turboModules: true
}
```
https://github.com/expo/expo/blob/bcd6ce42add44554d45cf1c060799ea64b646701/packages/%40expo/config-types/src/ExpoConfig.ts#L274

**Comment by mrousavy** [comment]
I guess - I don't use Expo.
Bare RN has new arch enabled by default for a long time now, not sure about Expo.

**Comment by marygarciapepperstone** [comment]
I encountered the same error and fixed it by setting this 

`newArchEnabled=true` on `gradle.properties`

**Comment by SohelIslamImran** [comment]
Using SDK 53
<img width="1312" alt="Image" src="https://github.com/user-attachments/assets/84e06077-31d5-4821-aaef-96c2bc657663" />

**Comment by gabimoncha** [comment]
I didn't have any issues with MMKV since updating to Expo 53.
@SohelIslamImran can you try this config in app.json

```
...
experiments: {
	turboModules: true
},
...
```

**Comment by philwu** [comment]
same issue here with Expo 53

![Image](https://github.com/user-attachments/assets/b3520d0a-9576-4f39-b250-68d8475c30bd)

![Image](https://github.com/user-attachments/assets/0641a788-bd0a-45ba-ad91-815f840ff4b1)

tried **experiments.turboModules** but no luck...

![Image](https://github.com/user-attachments/assets/6bfcb339-be36-4d8c-919f-8831773b92fa)

**Comment by philwu** [comment]
> Using SDK 53 <img alt="Image" width="1312" src="https://private-user-images.githubusercontent.com/76745339/441830426-84e06077-31d5-4821-aaef-96c2bc657663.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDg4NTI3NjIsIm5iZiI6MTc0ODg1MjQ2MiwicGF0aCI6Ii83Njc0NTMzOS80NDE4MzA0MjYtODRlMDYwNzctMzFkNS00ODIxLWFhZWYtOTZjMmJjNjU3NjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjAyVDA4MjEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2OGY5MmIyOGRjNWUxZDQzOTZhYjU5OTIxMmJhOTE4ZThmZjI1MjkxOTM4NmNlNWE5MmYyM2Y5NjExMWFlMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ga9iTBkWuhcQ3pwSVUJi-qZqpsykLxLfv06YfVUj3sI">


I think I know what's going on.

**react-native-mmkv DOES NOT support Expo Go**. 

You have to make a development build by Expo.

Specificlly, you need to run following commands in your project root
```
npx expo install expo-dev-client
npx expo run:android
```

**Comment by mrousavy** [comment]
I think this has been fixed in [react-native-mmkv 4.x.x-beta](https://github.com/mrousavy/react-native-mmkv/releases/tag/v4.0.0-beta.0).

You need to be on new architecture. Clean your cache and rebuild the native project.
