### ISSUE TITLE
Cannot build on Android React-native 0.80.0

### ISSUE THREAD

**Issue by FrancMihani** [mrousavy/react-native-mmkv#838]
Hello again, Sorry for not checking both platforms in the same time

Description:
I am trying to build a new app with react-native-mmkv and it fails to build on Android.

Error Details:
`error: incompatible types: MmkvPlatformContextModule cannot be converted to NativeModule return new MmkvPlatformContextModule(reactContext); ^ /node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:19: error: cannot find symbol if (name.equals(MmkvPlatformContextModule.NAME)) { ^ symbol: variable NAME location: class MmkvPlatformContextModule /node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:31: error: cannot find symbol MmkvPlatformContextModule.NAME, ^ symbol: variable NAME location: class MmkvPlatformContextModule /node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:33: error: cannot find symbol MmkvPlatformContextModule.NAME, ^ symbol: variable NAME location: class MmkvPlatformContextModule /node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:34: error: cannot find symbol MmkvPlatformContextModule.NAME, ^ symbol: variable NAME location: class MmkvPlatformContextModule /node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:15: error: method does not override or implement a method from a supertype @Override ^ /node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:21: error: method does not override or implement a method from a supertype @Override ^ /node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:7: error: cannot find symbol public class MmkvPlatformContextModule extends NativeMmkvPlatformContextSpec { ^ symbol: class NativeMmkvPlatformContextSpec 8 errors `

Environment:
react-native-mmkv version: 3.3
React Native version: 0.80.0
Platform: Android
Architecture: New Architecture, Hermes

Context:
The app wont build.
The error as in the details.
The project is brand new and there is no other modification on it.

**Comment by DimitrenkoNikolayFusion** [comment]
Same issue. 
react-native-mmkv version: 3.3.0 
react-native: 0.74.3 old architecture

**Comment by FrancMihani** [comment]
@mrousavy any update with this, or any workarounds ?

**Comment by mrousavy** [comment]
No, no update. I haven't looked at this yet.

**Comment by FrancMihani** [comment]
I upgraded the app to 0.80.1 still the same problem, but something weird in android even why the `newArchEnabled=true  hermesEnabled=true` , app runs using the Legacy Architecture. Even a fresh build runs in Legacy Architecture. Can this be the root of the problem?

**Comment by ThiaAlves** [comment]
Same issue here. I can build the app using version 2.12.2, but when I run it, I get the error: 'Failed to create a new MMKV instance.'

**Comment by FrancMihani** [comment]
@ThiaAlves I created an issue in react-native repo https://github.com/facebook/react-native/issues/52375 this might be a problem with new arch not being enabled even though `newArchEnabled=true`

**Comment by LJoel23** [comment]
I ran into the same issue, and in my case, the cause was a conflicting setting in my global Gradle properties.

💡 Solution:
Check your ~/.gradle/gradle.properties file — I had the following line there:

newArchEnabled=false

This overrides the project-level setting and disables the new architecture even if it's enabled in your project’s gradle.properties.

✅ After removing or updating this value in the global config, the issue was resolved.

Hope this helps others who might be stuck on the same problem!

**Comment by FrancMihani** [comment]
@LJoel23 thank you, yes this resolved the issue
