### ISSUE TITLE
Compilation fails for iOS

### ISSUE THREAD

**Issue by leoboyerbx** [mrousavy/react-native-mmkv#933]
When updating from v4 beta 11 to v4 stable, I got a compilation error. Downgrading to beta 11 fixes the issue:

```
› Executing expo-manifests Pods/EXManifests » Copy generated compatibility header

❌  (ios/Pods/Headers/Public/NitroMmkv/NitroMmkv-Swift-Cxx-Bridge.hpp:52:119)

  50 |    */
  51 |   using std__shared_ptr_HybridMMKVPlatformContextSpec_ = std::shared_ptr<HybridMMKVPlatformContextSpec>;
> 52 |   std::shared_ptr<HybridMMKVPlatformContextSpec> create_std__shared_ptr_HybridMMKVPlatformContextSpec_(void* NON_NULL swiftUnsafePointer) noexcept;
     |                                                                                                                       ^ expected ')'
  53 |   void* NON_NULL get_std__shared_ptr_HybridMMKVPlatformContextSpec_(std__shared_ptr_HybridMMKVPlatformContextSpec_ cppType);
  54 |   
  55 |   // pragma MARK: std::weak_ptr<HybridMMKVPlatformContextSpec>


❌  (ios/Pods/Headers/Public/NitroMmkv/NitroMmkv-Swift-Cxx-Bridge.hpp:53:17)

  51 |   using std__shared_ptr_HybridMMKVPlatformContextSpec_ = std::shared_ptr<HybridMMKVPlatformContextSpec>;
  52 |   std::shared_ptr<HybridMMKVPlatformContextSpec> create_std__shared_ptr_HybridMMKVPlatformContextSpec_(void* NON_NULL swiftUnsafePointer) noexcept;
> 53 |   void* NON_NULL get_std__shared_ptr_HybridMMKVPlatformContextSpec_(std__shared_ptr_HybridMMKVPlatformContextSpec_ cppType);
     |                 ^ expected ';' after top level declarator
  54 |   
  55 |   // pragma MARK: std::weak_ptr<HybridMMKVPlatformContextSpec>
  56 |   using std__weak_ptr_HybridMMKVPlatformContextSpec_ = std::weak_ptr<HybridMMKVPlatformContextSpec>;
```

I have removed the Podfile override since it's not needed, but it fails anyway.

**Comment by mrousavy** [comment]
I'm 99% sure you are on an old react-native-nitro-modules version. Update to latest react-native-nitro-modules (0.31.1 as of now)
