### ISSUE TITLE
Android Compilation Failed with 1.6.0

### ISSUE THREAD

**Issue by beetlebum** [mrousavy/react-native-mmkv#272]
Compilation error on Android after upgrading from 1.5.4 to 1.6.0. Downgrading to 1.5.4 solves the issue.

We have a setup with Reanimated 2 and followed the instructions in the guide (don't seem to have changed for this release).

Have tried adding `implementation project(':react-native-mmkv')` to the gradle file as in the example app, to no avail.

```
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /Users/XXX/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: ^6.1.0 => 6.3.1
    react: ^17.0.2 => 17.0.2
    react-native: ^0.67.0-rc.6 => 0.67.0-rc.6
    
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 30
    
```

```
/XXX/app/src/main/java/com/getpaired/app/PairedJSIPackage.java:7: error: package com.reactnativemmkv does not exist
import com.reactnativemmkv.MmkvModule;
                          ^
/XXX/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:91: error: package com.reactnativemmkv does not exist
import com.reactnativemmkv.MmkvPackage;
                          ^
/XXX/android/app/src/main/java/com/getpaired/app/PairedJSIPackage.java:15: error: cannot find symbol
        MmkvModule.install(jsContext, reactApplicationContext.getFilesDir().getAbsolutePath() + "/mmkv");
        ^
  symbol:   variable MmkvModule
  location: class PairedJSIPackage
/XXX/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:203: error: cannot find symbol
      new MmkvPackage(),
          ^
  symbol:   class MmkvPackage
  location: class PackageList
```

**Comment by mrousavy** [comment]
Hey Diego!

Hmm, that kinda looks like a cache issue though?

Did you try:

```
./gradlew clean
./gradlew assembleDebug
```

?

Also, check if `node_modules/react-native-mmkv/android` exists and has all of the source in there

**Comment by mrousavy** [comment]
Also run `npx react-native config` to see if `react-native-mmkv` is correctly detected to be autolinkable

**Comment by beetlebum** [comment]
I have tried to clean and assemble in different flavours but no luck.

``` 
"react-native-mmkv": {
      "root": "/Users/user/Code/GitHub/app/node_modules/react-native-mmkv",
      "name": "react-native-mmkv",
      "platforms": {
        "ios": {
          "sourceDir": "/Users/user/Code/GitHub/app/node_modules/react-native-mmkv/ios",
          "folder": "/Users/user/Code/GitHub/app/node_modules/react-native-mmkv",
          "pbxprojPath": "/Users/user/Code/GitHub/app/node_modules/react-native-mmkv/ios/Mmkv.xcodeproj/project.pbxproj",
          "podfile": null,
          "podspecPath": "/Users/user/Code/GitHub/app/node_modules/react-native-mmkv/react-native-mmkv.podspec",
          "projectPath": "/Users/user/Code/GitHub/app/node_modules/react-native-mmkv/ios/Mmkv.xcodeproj",
          "projectName": "Mmkv.xcodeproj",
          "libraryFolder": "Libraries",
          "sharedLibraries": [],
          "plist": [],
          "scriptPhases": [],
          "configurations": []
        },
        "android": {
          "sourceDir": "/Users/user/Code/GitHub/app/node_modules/react-native-mmkv/android",
          "folder": "/Users/user/Code/GitHub/app/node_modules/react-native-mmkv",
          "packageImportPath": "import com.reactnativemmkv.MmkvPackage;",
          "packageInstance": "new MmkvPackage()",
          "buildTypes": []
        }
      },
      "assets": [],
      "hooks": {},
      "params": []
    },
```

The code is all there in node_modules:
```
ls /Users/user/Code/GitHub/app/node_modules/react-native-mmkv/android
CMakeLists.txt    build.gradle      gradle.properties src

ls /Users/user/Code/GitHub/app/node_modules/react-native-mmkv/android/src/main/java/com/reactnativemmkv
MmkvModule.java        MmkvModulePackage.java MmkvPackage.java

```

**Comment by fahad86** [comment]
is it because jcenter stopped operation and react-native-mmkv still uses jcenter??

**Comment by mrousavy** [comment]
Hey! Can you check if #273 solves the issue for you? Remember to do a clean and rebuild.

**Comment by beetlebum** [comment]
works fine now, thanks
